name: Project tests
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test-angular:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

  test-cdk:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cdk

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
